// flow-typed signature: 6703cfe331126c339aeab68c385102f4
// flow-typed version: <<STUB>>/babel-plugin-recharts_v^1.1.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-recharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-recharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-recharts/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-recharts/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-recharts/lib/index'>;
}
