// flow-typed signature: 25ac7847ef3224fdaadb1e26c8fc5485
// flow-typed version: <<STUB>>/randexp_v^0.4.5/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randexp/lib/randexp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randexp/lib/randexp.js' {
  declare module.exports: $Exports<'randexp/lib/randexp'>;
}
