export const TOGGLE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';
export const TOGGLE_FETCHING = 'UPDATE_FETCHING';
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';
export const POPULATE_LANG_DATA = 'POPULATE_LANG_DATA';
export const POPULATE_OFFICE_DATA = 'POPULATE_OFFICE_DATA';
export const POPULATE_NAV_DATA = 'POPULATE_NAV_DATA';
export const POPULATE_ZIP_DATA = 'POPULATE_ZIP_DATA';
